#ifndef NECESSARYINFOFORM_H
#define NECESSARYINFOFORM_H

#include <QWidget>

namespace Ui {
class NecessaryInfoForm;
}

//Autogenerated by Qt
class NecessaryInfoForm : public QWidget
{
    Q_OBJECT

public:
    explicit NecessaryInfoForm(QWidget *parent = nullptr); //Autogenerated by Qt
    ~NecessaryInfoForm(); //Autogenerated by Qt



private slots: //various functions dependent on interactions from the parent GUI & received signals
    void on_buttonConfirm_clicked(); //used when the button to create a new contact is clicked (does not directly handle creating the contact)
    void on_buttonCancel_clicked(); //used to close the required info form without adding a new contact
    void open_NecI_GUI(); //a slot which listens for an event of the same name from mainwindow to display the required info form
    void on_Profilepic_clicked(); //used to get image file input from user
    //functions that send out information to other windows
signals:
    void new_Contact_Info(const QIcon icon, const QString &text); //Sends contact info

private:
    Ui::NecessaryInfoForm *ui;

};

#endif // NECESSARYINFOFORM_H
